version: "3.8"

services:
  gpu-monitor:
    build: .
    container_name: gpu-monitor
    ports:
      - "8080:8080"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/host_proc:ro
    environment:
      - HOST_PROC=/host_proc
    pid: "host"
    restart: unless-stopped
