version: "3.8"

services:
  gpu-monitor:
    build: .
    container_name: gpu-monitor
    ports:
      - "8080:8080"
    runtime: nvidia
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
